In [1]:
import pandas as pd
import numpy as np

## Duplicates in Datasets


In [2]:
students = [('Sri',    34, 'Sydeny'),
            ('Sai',    30, 'Delhi'),
            ('Anand',  16, 'Singapore'),
            ('Steve',  30, 'Delhi'),
            ('Anand',   16, 'Singapore'),
            ('Priti',    30, 'Mumbai'),
            ('Rahul', 40, 'Delhi'),
            ('Rahul', 30, 'Delhi'),
            ('Anand',   16, 'Singapore'),
            ]
 
# Create a DataFrame object
df = pd.DataFrame(students, columns=['Name', 'Age', 'City'])
df

Name  Age       City
0    Sri   34     Sydeny
1    Sai   30      Delhi
2  Anand   16  Singapore
3  Steve   30      Delhi
4  Anand   16  Singapore
5  Priti   30     Mumbai
6  Rahul   40      Delhi
7  Rahul   30      Delhi
8  Anand   16  Singapore

## Find Duplicate Rows based on all columns

In [3]:
# Select duplicate rows except first occurrence based on all columns
duplicateRowsDF = df[df.duplicated(keep='first')]

print("Duplicate Rows except first occurrence based on all columns are :")
duplicateRowsDF

Duplicate Rows except first occurrence based on all columns are :


Name  Age       City
4  Anand   16  Singapore
8  Anand   16  Singapore

In [6]:
# Select duplicate rows except last occurrence based on all columns
duplicateRowsDF = df[df.duplicated(keep='last')]
 
print("Duplicate Rows except last occurrence based on all columns are :")
duplicateRowsDF

Duplicate Rows except last occurrence based on all columns are :


Name  Age       City
2  Anand   16  Singapore
4  Anand   16  Singapore

## Find Duplicate Rows based on selected columns

#### find & select rows based on a single column,

In [7]:
# Select all duplicate rows based on one column
duplicateRowsDF = df[df.duplicated(['Name'], keep='first')]
duplicateRowsDF

Name  Age       City
4  Anand   16  Singapore
7  Rahul   30      Delhi
8  Anand   16  Singapore

Here rows which has same value in ‘Name’ column are marked as duplicate and returned.

#### Find & select rows based on a two column names,

In [8]:
# Select all duplicate rows based on multiple column names in list
duplicateRowsDF = df[df.duplicated(['Age', 'City'], keep='first')]
duplicateRowsDF

Name  Age       City
3  Steve   30      Delhi
4  Anand   16  Singapore
7  Rahul   30      Delhi
8  Anand   16  Singapore

Here rows which has same values in ‘Age’  & ‘City’ columns are marked as duplicate and returned.

## Dropping duplicates from a particular column

In [9]:
students = [('Sri',    34, 'Sydeny'),
            ('Sai',    30, 'Delhi'),
            ('Anand',  16, 'Singapore'),
            ('Steve',  30, 'Delhi'),
            ('Anand',   16, 'Singapore'),
            ('Priti',    30, 'Mumbai'),
            ('Rahul', 40, 'Delhi'),
            ('Rahul', 30, 'Delhi')
            ]
 
# Create a DataFrame object
df = pd.DataFrame(students, columns=['Name', 'Age', 'City'])
df

Name  Age       City
0    Sri   34     Sydeny
1    Sai   30      Delhi
2  Anand   16  Singapore
3  Steve   30      Delhi
4  Anand   16  Singapore
5  Priti   30     Mumbai
6  Rahul   40      Delhi
7  Rahul   30      Delhi

In [12]:
df.drop_duplicates(['Name'], keep='first', inplace=True)

In [13]:
df

Name  Age       City
0    Sri   34     Sydeny
1    Sai   30      Delhi
2  Anand   16  Singapore
3  Steve   30      Delhi
5  Priti   30     Mumbai
6  Rahul   40      Delhi

In [ ]:
df.drop_duplicates(['Name', 'City'], keep='first', inplace=False)

In [14]:
?df.drop_duplicates

## Basic sanity of data

In [15]:
import sklearn
from sklearn import datasets

In [16]:
iris = datasets.load_iris()

In [17]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [19]:
iris.data[:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [18]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [20]:
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [21]:
X = iris.data
y = iris.target

In [23]:
X[:3]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2]])

In [24]:
y[:3]

array([0, 0, 0])

In [22]:
np.c_[X[:3], y[:3]]

array([[5.1, 3.5, 1.4, 0.2, 0. ],
       [4.9, 3. , 1.4, 0.2, 0. ],
       [4.7, 3.2, 1.3, 0.2, 0. ]])

In [25]:
data    = np.c_[X, y]
columns = ['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'class']

df      = pd.DataFrame(data=data, columns=columns)
df.head()



sepal_length  sepal_width  petal_length  petal_width  class
0           5.1          3.5           1.4          0.2    0.0
1           4.9          3.0           1.4          0.2    0.0
2           4.7          3.2           1.3          0.2    0.0
3           4.6          3.1           1.5          0.2    0.0
4           5.0          3.6           1.4          0.2    0.0

In [26]:
# change the class from numeric to string for easy understanding
replacements  = {0: 'setosa', 1: 'versicolor', 2: 'virginica'}

df['class']   = df['class'].map(replacements)

In [28]:
df.head()

sepal_length  sepal_width  petal_length  petal_width   class
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [29]:
# find out how many samples from each class
df['class'].value_counts()

virginica     50
versicolor    50
setosa        50
Name: class, dtype: int64

In [30]:
# basic statistics
# check for min, max, quartiles, IQR
df.describe()

sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.057333      3.758000     1.199333
std        0.828066     0.435866      1.765298     0.762238
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [31]:
df[['sepal_length', 'petal_length']].describe()

sepal_length  petal_length
count    150.000000    150.000000
mean       5.843333      3.758000
std        0.828066      1.765298
min        4.300000      1.000000
25%        5.100000      1.600000
50%        5.800000      4.350000
75%        6.400000      5.100000
max        7.900000      6.900000

In [ ]:
# locate by index position
df.loc[[0, 56]]

In [ ]:
df.loc[df['class'] == 'setosa']

In [ ]:
# display selected columns for class = 'setosa'
df.loc[df['class'] == 'setosa', ['petal_width', 'petal_length']]

In [ ]:
# display mean values of selected columns for class = 'setosa'
df.loc[df['class'] == 'setosa', ['petal_width', 'petal_length']].mean()

In [ ]:
# display max values of selected columns for class = 'setosa'
df.loc[df['class'] == 'setosa', ['petal_width', 'petal_length']].max()

In [ ]:
# use of grouping
groups = df.groupby('class')

In [ ]:
# use sum(), min(), max(), count()
groups.mean()

In [ ]:
groups.agg(['mean', 'min', 'max', 'count'])

## numeric col containing non-numeric data

In [32]:
d = {
 'unit': ['UD', 'UD', 'UD', 'UD', 'ud','uD'],
 'N-D':  [ 'Q1', 'Q2', 'Q3', 'Q4','Q5','Q6'],
 'num' : [ -1.48, 1.7, -6.18, 0.25, 'weird', 0.25]

}

df = pd.DataFrame(d)
df

unit N-D    num
0   UD  Q1  -1.48
1   UD  Q2    1.7
2   UD  Q3  -6.18
3   UD  Q4   0.25
4   ud  Q5  weird
5   uD  Q6   0.25

In [41]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   unit    6 non-null      object
 1   N-D     6 non-null      object
 2   num     6 non-null      object
dtypes: object(3)
memory usage: 272.0+ bytes


In [42]:
df['num'].str.isnumeric()

0      NaN
1      NaN
2      NaN
3      NaN
4    False
5      NaN
Name: num, dtype: object

In [34]:
df['num'].str.isdecimal()

0      NaN
1      NaN
2      NaN
3      NaN
4    False
5      NaN
Name: num, dtype: object

## check for character cases

In [35]:
df['unit'].str.isupper()

0     True
1     True
2     True
3     True
4    False
5    False
Name: unit, dtype: bool

In [36]:
df['unit'] = df['unit'].str.upper()

In [37]:
df

unit N-D    num
0   UD  Q1  -1.48
1   UD  Q2    1.7
2   UD  Q3  -6.18
3   UD  Q4   0.25
4   UD  Q5  weird
5   UD  Q6   0.25

## Handling missing values

In [43]:
location = r"data\nba.csv"

In [66]:
# making data frame from csv file 
nba = pd.read_csv(r"data\nba.csv") 

In [45]:
nba.shape

(457, 9)

In [46]:
nba.head(3)

Name            Team  Number Position   Age Height  Weight  \
0  Avery Bradley  Boston Celtics     0.0       PG  25.0    6-2   180.0   
1    Jae Crowder  Boston Celtics    99.0       SF  25.0    6-6   235.0   
2   John Holland  Boston Celtics    30.0       SG  27.0    6-5   205.0   

             College     Salary  
0              Texas  7730337.0  
1          Marquette  6796117.0  
2  Boston University        NaN

In [49]:
# are there nulls?
nba.isnull().sum()

Name         0
Team         0
Number       0
Position     0
Age          0
Height       0
Weight       0
College     84
Salary      11
dtype: int64

example #1 - Replacing NaN values with a Static value.

In [50]:
# replacing na values in college with No college 
nba["College"].fillna("MIT", inplace = True) 

nba.isnull().sum()
#nba['College'].isnull().sum()

Name         0
Team         0
Number       0
Position     0
Age          0
Height       0
Weight       0
College      0
Salary      11
dtype: int64

Example #2: Using method Parameter

In [51]:
# making data frame from csv file 
nba = pd.read_csv(location) 
nba.head(10)

Name            Team  Number Position   Age Height  Weight  \
0  Avery Bradley  Boston Celtics     0.0       PG  25.0    6-2   180.0   
1    Jae Crowder  Boston Celtics    99.0       SF  25.0    6-6   235.0   
2   John Holland  Boston Celtics    30.0       SG  27.0    6-5   205.0   
3    R.J. Hunter  Boston Celtics    28.0       SG  22.0    6-5   185.0   
4  Jonas Jerebko  Boston Celtics     8.0       PF  29.0   6-10   231.0   
5   Amir Johnson  Boston Celtics    90.0       PF  29.0    6-9   240.0   
6  Jordan Mickey  Boston Celtics    55.0       PF  21.0    6-8   235.0   
7   Kelly Olynyk  Boston Celtics    41.0        C  25.0    7-0   238.0   
8   Terry Rozier  Boston Celtics    12.0       PG  22.0    6-2   190.0   
9   Marcus Smart  Boston Celtics    36.0       PG  22.0    6-4   220.0   

             College      Salary  
0              Texas   7730337.0  
1          Marquette   6796117.0  
2  Boston University         NaN  
3      Georgia State   1148640.0  
4                NaN   5000000.0  
5                NaN  12000000.0  
6                LSU   1170960.0  
7            Gonzaga   2165160.0  
8         Louisville   1824360.0  
9     Oklahoma State   3431040.0

In [53]:
# making data frame from csv file 
nba = pd.read_csv(location) 
  
# replacing na values in college with No college 
nba["College"].fillna( method ='fill', inplace = True) 
  
nba.head(10)

Name            Team  Number Position   Age Height  Weight  \
0  Avery Bradley  Boston Celtics     0.0       PG  25.0    6-2   180.0   
1    Jae Crowder  Boston Celtics    99.0       SF  25.0    6-6   235.0   
2   John Holland  Boston Celtics    30.0       SG  27.0    6-5   205.0   
3    R.J. Hunter  Boston Celtics    28.0       SG  22.0    6-5   185.0   
4  Jonas Jerebko  Boston Celtics     8.0       PF  29.0   6-10   231.0   
5   Amir Johnson  Boston Celtics    90.0       PF  29.0    6-9   240.0   
6  Jordan Mickey  Boston Celtics    55.0       PF  21.0    6-8   235.0   
7   Kelly Olynyk  Boston Celtics    41.0        C  25.0    7-0   238.0   
8   Terry Rozier  Boston Celtics    12.0       PG  22.0    6-2   190.0   
9   Marcus Smart  Boston Celtics    36.0       PG  22.0    6-4   220.0   

             College      Salary  
0              Texas   7730337.0  
1          Marquette   6796117.0  
2  Boston University         NaN  
3      Georgia State   1148640.0  
4                LSU   5000000.0  
5                LSU  12000000.0  
6                LSU   1170960.0  
7            Gonzaga   2165160.0  
8         Louisville   1824360.0  
9     Oklahoma State   3431040.0

Similarly, bfill (backfill) method can also be used.

Example #3: Using mean value

In [54]:
# making data frame from csv file 
nba = pd.read_csv(location) 

In [55]:
nba.isnull().sum()

Name         0
Team         0
Number       0
Position     0
Age          0
Height       0
Weight       0
College     84
Salary      11
dtype: int64

In [56]:
# Or, depending on your needs:
nba['Salary'] = nba['Salary'].fillna(nba['Salary'].mean())
nba['Salary'] = nba['Salary'].fillna(nba['Salary'].min())
nba['Salary'] = nba['Salary'].fillna(nba['Salary'].max())

In [57]:
nba.isnull().sum()

Name         0
Team         0
Number       0
Position     0
Age          0
Height       0
Weight       0
College     84
Salary       0
dtype: int64

In [58]:
np.set_printoptions(suppress=True) 

In [59]:
nba.Salary.sample(15)

123      206192.0
189    16000000.0
339    22192730.0
335     2139000.0
298     5250000.0
406      947276.0
12      3425510.0
7       2165160.0
254     2288205.0
25       947276.0
51      1074169.0
445     3777720.0
450     2050000.0
347      525093.0
202     1358880.0
Name: Salary, dtype: float64

In [ ]:
nba['Age'] = nba['Age'].fillna(200)

In [ ]:
nba[nba['Age']==200]

In [60]:
raw_data = {'first_name': ['Jason', np.nan, 'Tina', 'Jake', 'Amy'], 
            'last_name': ['Miller', np.nan, 'Ali', 'Milner', 'Cooze'], 
            'age': [42, np.nan, 36, 24, 73], 
            'sex': ['m', np.nan, 'f', 'm', 'f'], 
            'preTestScore': [4, np.nan, np.nan, 2, 3],
            'postTestScore': [np.nan, np.nan, np.nan, np.nan, np.nan]}

df = pd.DataFrame(raw_data, columns = ['first_name', 'last_name', 'age', 'sex', 'preTestScore', 'postTestScore'])
df

first_name last_name   age  sex  preTestScore  postTestScore
0      Jason    Miller  42.0    m           4.0            NaN
1        NaN       NaN   NaN  NaN           NaN            NaN
2       Tina       Ali  36.0    f           NaN            NaN
3       Jake    Milner  24.0    m           2.0            NaN
4        Amy     Cooze  73.0    f           3.0            NaN

In [61]:
# Drop missing observations
# rows returned after dropping, the original df remains intact
df_no_missing = df.dropna()
df_no_missing

Empty DataFrame
Columns: [first_name, last_name, age, sex, preTestScore, postTestScore]
Index: []

In [ ]:
df

In [62]:
#Drop rows where all cells in that row is NA
df_cleaned = df.dropna(how='all')
df_cleaned

first_name last_name   age sex  preTestScore  postTestScore
0      Jason    Miller  42.0   m           4.0            NaN
2       Tina       Ali  36.0   f           NaN            NaN
3       Jake    Milner  24.0   m           2.0            NaN
4        Amy     Cooze  73.0   f           3.0            NaN

In [63]:
# Create a new column full of missing values
df['location'] = np.nan
df

first_name last_name   age  sex  preTestScore  postTestScore  location
0      Jason    Miller  42.0    m           4.0            NaN       NaN
1        NaN       NaN   NaN  NaN           NaN            NaN       NaN
2       Tina       Ali  36.0    f           NaN            NaN       NaN
3       Jake    Milner  24.0    m           2.0            NaN       NaN
4        Amy     Cooze  73.0    f           3.0            NaN       NaN

In [64]:
# Drop column if they only contain missing values
df.dropna(axis=1, how='all')

first_name last_name   age  sex  preTestScore
0      Jason    Miller  42.0    m           4.0
1        NaN       NaN   NaN  NaN           NaN
2       Tina       Ali  36.0    f           NaN
3       Jake    Milner  24.0    m           2.0
4        Amy     Cooze  73.0    f           3.0

In [ ]:
# Drop rows that contain less than five observations
# This is really mostly useful for time series
df

In [65]:
df.dropna(thresh=5)

first_name last_name   age sex  preTestScore  postTestScore  location
0      Jason    Miller  42.0   m           4.0            NaN       NaN
3       Jake    Milner  24.0   m           2.0            NaN       NaN
4        Amy     Cooze  73.0   f           3.0            NaN       NaN

In [ ]:
# Fill in missing data with zeros
df.fillna(1000)

In [ ]:
# Fill in missing in preTestScore with the mean value of preTestScore
# inplace=True means that the changes are saved to the df right away

In [ ]:
df["preTestScore"].fillna(df["preTestScore"].mean(), inplace=True)
df

In [ ]:
# Fill in missing in postTestScore with each sex’s mean value of postTestScore
df["postTestScore"].fillna(df.groupby("sex")["postTestScore"].transform("mean"), inplace=True)
df

## HOME WORK : Using scikit learn imputer

strategy : string, optional (default=”mean”)
The imputation strategy.

- If “mean”, then replace missing values using the mean along each column. Can only be used with numeric data.
- If “median”, then replace missing values using the median along each column. Can only be used with numeric data.
- If “most_frequent”, then replace missing using the most frequent value along each column. Can be used with strings or numeric data.
- If “constant”, then replace missing values with fill_value. Can be used with strings or numeric data.

In [ ]:
#from sklearn.impute import SimpleImputer
from sklearn.preprocessing import Imputer

df = pd.DataFrame([[10,     20],
                   [np.nan, 23],
                   [15,    np.nan],
                   [17,    29]])

df.dtypes

In [ ]:
imp = SimpleImputer(strategy="median")

print(imp.fit_transform(df)) 

one more example ...

In [ ]:
X = np.array([[23.56],
              [53.45],
              ['NaN'],
              [44.44],
              [77.78],
              ['NaN'],
              [234.44],
              [11.33],
              [79.87]])

In [ ]:
imputer = SimpleImputer(strategy='mean')  

imputer.fit_transform(X)

one more example ..

In [ ]:
# Create an empty dataset
df = pd.DataFrame()

# Create two variables called x0 and x1. Make the first value of x1 a missing value
df['x0'] = [0.3051,0.4949,0.6974,0.3769,0.2231,0.341,0.4436,0.5897,0.6308,0.5]
df['x1'] = [np.nan,0.2654,0.2615,0.5846,0.4615,0.8308,0.4962,0.3269,0.5346,0.6731]

# View the dataset
df

In [ ]:
# Fit Imputer
# Create an imputer object that looks for 'Nan' values, then replaces them with the mean value of the feature by columns (axis=0)
mean_imputer = Imputer(missing_values='NaN', strategy='mean', axis=0)

# Train the imputor on the df dataset
mean_imputer = mean_imputer.fit(df)

In [ ]:
# Apply Imputer
# Apply the imputer to the df dataset
imputed_df = mean_imputer.transform(df.values)

In [ ]:
imputed_df

Notice that 0.49273333 is the imputed value, replacing the np.NaN value.