# <center> Ensemble Learning - Stacking

### Importing Libraries

In [1]:
#importing necessary libraries
import numpy as np
import pandas as pd
import statistics as st

### Importing Dataset

In [2]:
data = pd.read_csv('data/data_cleaned.csv')

#printing the first few rows
data.head()

Survived   Age     Fare  Pclass_1  Pclass_2  Pclass_3  Sex_female  \
0         0  22.0   7.2500         0         0         1           0   
1         1  38.0  71.2833         1         0         0           1   
2         1  26.0   7.9250         0         0         1           1   
3         1  35.0  53.1000         1         0         0           1   
4         0  35.0   8.0500         0         0         1           0   

   Sex_male  SibSp_0  SibSp_1  ...  Parch_0  Parch_1  Parch_2  Parch_3  \
0         1        0        1  ...        1        0        0        0   
1         0        0        1  ...        1        0        0        0   
2         0        1        0  ...        1        0        0        0   
3         0        0        1  ...        1        0        0        0   
4         1        1        0  ...        1        0        0        0   

   Parch_4  Parch_5  Parch_6  Embarked_C  Embarked_Q  Embarked_S  
0        0        0        0           0           0           1  
1        0        0        0           1           0           0  
2        0        0        0           0           0           1  
3        0        0        0           0           0           1  
4        0        0        0           0           0           1  

[5 rows x 25 columns]

In [3]:
#size of the data
data.shape

(891, 25)

In [4]:
#checking missing values
data.isnull().sum()

Survived      0
Age           0
Fare          0
Pclass_1      0
Pclass_2      0
Pclass_3      0
Sex_female    0
Sex_male      0
SibSp_0       0
SibSp_1       0
SibSp_2       0
SibSp_3       0
SibSp_4       0
SibSp_5       0
SibSp_8       0
Parch_0       0
Parch_1       0
Parch_2       0
Parch_3       0
Parch_4       0
Parch_5       0
Parch_6       0
Embarked_C    0
Embarked_Q    0
Embarked_S    0
dtype: int64

### Separating Dependent and Independent Variables

In [5]:
#independent variables
x = data.drop(["Survived"], axis = 1)

#dependent variables
y = data['Survived']

x.shape, y.shape

((891, 24), (891,))

### Making test and training set

In [6]:
from sklearn.model_selection import train_test_split as tts

train_x, test_x, train_y, test_y = tts (x, y, random_state = 9 , stratify = y, test_size=0.2)
train_x.shape, test_x.shape, train_y.shape, test_y.shape

((712, 24), (179, 24), (712,), (179,))

## Base models 

In [7]:
#importing predictive models
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier

### Model Training and Predictions 

In [8]:
def model_predictions(model, train_x, train_y, test_x):
    
    #train the model
    model.fit(train_x,train_y)
    
    #storing predictions for train and test
    pred_train=model.predict(train_x)
    pred_test=model.predict(test_x)
    return pred_train, pred_test

## Model 1 - Decision Tree

In [9]:
DT=DecisionTreeClassifier(random_state= 101)
M1_train, M1_test = model_predictions(DT, train_x, train_y, test_x)

## Model 2 - Logistic Regression

In [ ]:
#Feature Scaling
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaler.fit(X=train_x)

train_x = scaler.transform(train_x)
test_x = scaler.transform(test_x)

In [10]:
LR=LogisticRegression(random_state= 101)
M2_train, M2_test = model_predictions(LR, train_x, train_y, test_x)

C:\Users\pogupt\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


## Model 3 - k Nearest Neighbour

In [11]:
knn=KNeighborsClassifier()
M3_train, M3_test = model_predictions(knn, train_x, train_y, test_x)

## Method -1 : Max Voting

In [12]:
final_pred=np.array([])
final_pred

array([], dtype=float64)

In [13]:
for i in range(len(test_y)):
    final_pred=np.append(final_pred,st.mode([M1_test[i],M2_test[i],M3_test[i]]))

In [14]:
final_pred

array([1., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 1.,
       1., 0., 1., 1., 1., 1., 0., 0., 1., 0., 0., 0., 1., 0., 0., 1., 1.,
       1., 0., 0., 0., 1., 0., 0., 1., 1., 0., 1., 0., 1., 0., 0., 0., 0.,
       0., 1., 0., 1., 0., 0., 1., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0.,
       1., 0., 0., 0., 0., 1., 0., 1., 1., 0., 1., 0., 0., 0., 0., 0., 1.,
       0., 0., 0., 1., 1., 0., 1., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
       1., 0., 1., 0., 0., 1., 1., 1., 1., 0., 1., 1., 0., 1., 0., 1., 0.,
       0., 0., 0., 1., 0., 1., 1., 1., 0., 1., 1., 0., 0., 1., 0., 1., 1.,
       1., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
       1., 1., 0., 0., 1., 0., 1., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 1., 0., 0., 0., 0.])

## Method - 2 : Averaging

In [15]:
final_pred=((M1_test+M2_test+M3_test)/3).round(2)
final_pred

array([1.  , 0.  , 0.  , 1.  , 0.  , 0.  , 0.  , 0.67, 0.  , 0.  , 0.  ,
       0.  , 0.  , 0.  , 1.  , 0.33, 0.67, 1.  , 0.33, 1.  , 0.67, 0.67,
       0.67, 0.33, 0.  , 0.67, 0.  , 0.  , 0.  , 1.  , 0.  , 0.  , 1.  ,
       1.  , 0.67, 0.  , 0.  , 0.33, 1.  , 0.  , 0.33, 0.67, 1.  , 0.  ,
       1.  , 0.  , 1.  , 0.33, 0.  , 0.  , 0.  , 0.33, 1.  , 0.  , 0.67,
       0.  , 0.  , 0.67, 0.  , 0.33, 0.67, 0.  , 0.67, 0.  , 0.33, 0.33,
       0.  , 0.  , 1.  , 0.33, 0.  , 0.  , 0.  , 0.67, 0.  , 0.67, 1.  ,
       0.  , 0.67, 0.  , 0.  , 0.  , 0.  , 0.33, 0.67, 0.  , 0.  , 0.33,
       0.67, 0.67, 0.33, 0.67, 0.67, 0.33, 0.  , 0.  , 0.  , 0.  , 0.67,
       0.  , 0.  , 0.33, 0.67, 0.  , 0.67, 0.33, 0.  , 1.  , 0.67, 1.  ,
       1.  , 0.  , 0.67, 1.  , 0.  , 1.  , 0.  , 0.67, 0.33, 0.  , 0.33,
       0.33, 0.67, 0.  , 0.67, 0.67, 0.67, 0.  , 1.  , 0.67, 0.  , 0.  ,
       0.67, 0.33, 0.67, 1.  , 0.67, 1.  , 0.  , 0.  , 0.33, 0.33, 1.  ,
       0.  , 0.  , 0.33, 0.  , 0.  , 0.  , 0.67, 0.

## Method - 3 : Weighted Average

In [16]:
final_pred=(.3*M1_test+.3*M2_test+.4*M3_test).round(2)
final_pred

array([1. , 0. , 0. , 1. , 0. , 0. , 0. , 0.6, 0. , 0. , 0. , 0. , 0. ,
       0. , 1. , 0.3, 0.6, 1. , 0.4, 1. , 0.7, 0.6, 0.7, 0.4, 0. , 0.6,
       0. , 0. , 0. , 1. , 0. , 0. , 1. , 1. , 0.6, 0. , 0. , 0.4, 1. ,
       0. , 0.4, 0.6, 1. , 0. , 1. , 0. , 1. , 0.4, 0. , 0. , 0. , 0.3,
       1. , 0. , 0.6, 0. , 0. , 0.7, 0. , 0.4, 0.6, 0. , 0.6, 0. , 0.4,
       0.3, 0. , 0. , 1. , 0.3, 0. , 0. , 0. , 0.6, 0. , 0.6, 1. , 0. ,
       0.6, 0. , 0. , 0. , 0. , 0.4, 0.7, 0. , 0. , 0.3, 0.7, 0.6, 0.3,
       0.7, 0.6, 0.4, 0. , 0. , 0. , 0. , 0.6, 0. , 0. , 0.3, 0.6, 0. ,
       0.6, 0.4, 0. , 1. , 0.7, 1. , 1. , 0. , 0.7, 1. , 0. , 1. , 0. ,
       0.6, 0.4, 0. , 0.3, 0.4, 0.7, 0. , 0.6, 0.7, 0.7, 0. , 1. , 0.6,
       0. , 0. , 0.6, 0.4, 0.6, 1. , 0.7, 1. , 0. , 0. , 0.3, 0.4, 1. ,
       0. , 0. , 0.4, 0. , 0. , 0. , 0.6, 0. , 0. , 0. , 1. , 1. , 0. ,
       0. , 0.7, 0. , 0.6, 0. , 0.7, 0.4, 0. , 1. , 0. , 0. , 0. , 0. ,
       0.3, 0. , 0.4, 0.4, 0. , 0.7, 0.4, 0. , 0.4, 0. ])